version: "3"
services:
    queryapi:
        image: queryapi_img
        build:
            context: ./app
        ports:
            - '5679'
        environment:
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
        volumes:
            - queryapidata:/usr/src/app
        networks:
            - applayer
        restart: always
        healthcheck:
            test: curl --fail http://localhost:5679/poll || kill 1
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 20s
    nginx:
        image: nginx:latest
        container_name: nginx_inst
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports: 
            - '2026:2026'
        networks:
            - applayer
        depends_on:
            - queryapi
networks:
    applayer:
        driver: bridge
volumes:
    queryapidata: